package es.unizar.iaaa.pid.domain.enumeration;

/**
 * The ProcessStatus enumeration.
 */
public enum ProcessStatus {
    PENDING_PREPARING_HARVEST, PREPARING_HARVEST, PENDING_HARVEST, HARVEST, PENDING_TRANSFERRING_HARVEST, TRANSFERRING_HARVEST, PENDING_VALIDATION_BY_ID, VALIDATION_BY_ID, PENDING_TRANSFERRING_VALIDATION_BY_ID, TRANSFERRING_VALIDATION_BY_ID, PENDING_VALIDATION_END, VALIDATION_END, VALIDATION_BEGIN, NONE, UPDATING_PIDS
}
