version: '2'
services:
    pidms-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/pidms/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=pidms
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
