package es.unizar.iaaa.pid.config.harvester;

public enum States {
    PREPARING_HARVEST_LAUNCHED,
    HARVEST_LAUNCHED,
    TRANSFERRING_HARVEST_LAUNCHED,
    VALIDATION_BY_ID_LAUNCHED,
    TRANSFERRING_VALIDATION_BY_ID_LAUNCHED,
    FINISH_VALIDATION_LAUNCHED,
    RUNNING,
    END,
    STARTUP,
    MARKED_FOR_VALIDATION
}
